server:
  port: 9090
  error:
    include-stacktrace: never
    include-message: always

spring:
  datasource:
    url: jdbc:h2:mem:techdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true

logging:
  level:
    com.tech.exam: debug